name: waitingboard
description: "An cross platform app used to update and monitor provider wait times."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # firebase_core: ^3.9.0 
  # cloud_firestore: ^5.4.4
  multi_select_flutter: ^4.1.3
  syncfusion_flutter_xlsio: ^27.1.57
  http: ^1.2.2
  html: ^0.15.5
  path_provider: ^2.1.5
  # firebase_database: #^11.1.4 
  # firebase_storage: #12.3.4 
  # firebase_auth: ^5.3.1 
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  mysql1: ^0.20.0
  crypto: ^3.0.6
  package_info_plus: ^9.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  windows:
    image_path: "assets/icons/waitboard.ico"


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/waitboard.png  # If using PNG version
    - assets/icons/waitboard.ico  # If using ICO version
